name: Run tests

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: run tests

        run: python -m unittest discover

      - name: run type checking

        run: mypy hc_fib_pay

# trigger build (8-7-2023)
